config/routes.rb
Rails.application.routes.draw do
  resources :ailments

  resources :recipes

  root 'ailments#index'

end

app/models/ailment.rb
class Ailment < ActiveRecord::Base
	has_many :ailment_recipes
	has_many :recipes, through: :ailment_recipes
end

app/models/ailment_recipe.rb
class AilmentRecipe < ActiveRecord::Base
  belongs_to :ailment
  belongs_to :recipe

  # def Ailment_recipes
  # 	ailment_recipes = Ailment_recipes.create
  # end
end

app/models/parser.rb
require 'csv'


class Parser

  def initialize(file_path)
    @file_path = file_path
  end

  def ailments_list
    CSV.foreach(@file_path) do |row|
      new_row = row.join(",")      
      id, name, created_at, updated_at  = new_row.split(",")
      ailment = Ailment.create(:id => id.strip.to_i, :name => name.strip, :created_at => created_at.strip.to_i, :updated_at => updated_at.strip.to_i)           
    end
  end

  def recipes_list
    CSV.foreach(@file_path) do |row|
      new_row = row.join(",")     
      id, name, description, created_at, updated_at, url  = new_row.split(",")
      recipe = Recipe.create(:id => id.strip.to_i, :name => name.strip, :description => description.strip, :created_at => created_at.strip.to_i, :updated_at => updated_at.strip.to_i, :url => url.strip)
    end
  end

  def ailmentrecipes_list
    CSV.foreach(@file_path) do |row|
      new_row = row.join(",")     
      id, ailment_id, recipe_id, created_at, updated_at  = new_row.split(",")
      ailmentrecipe = AilmentRecipe.create(:id => id.strip.to_i, :ailment_id => ailment_id.strip.to_i, :recipe_id => recipe_id.strip.to_i, :created_at => created_at.to_i, :updated_at => updated_at.to_i)
    end
  end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :ailment_recipes
	has_many :ailments, through: :ailment_recipes
end

app/controllers/ailments_controller.rb
class AilmentsController < ApplicationController
  def index
  	@ailments = Ailment.all
  end

  def update
  	@ailment = Ailment.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
#fix indentation!!!!!

class RecipesController < ApplicationController
  def index

    affliction = nil
  	  if params[:search].size == 0
       @recipes = []
     # elsif params[:search].--- if ailment not in db?
     #  @recipes = []
     # elsif params[:search].include(:ailment)
        flash[:error] = "Please enter an ailment."
      else
        # based on name that's passed in, look up ailment, then ask for its recipes - get recipes for particular affliction
        #want to have a case-insensitive find_by for ActiveRecord -- change find by to where method
        if affliction = Ailment.where("lower(name) = ?", params[:search].downcase).first
          randomly_selected_recipe = affliction.recipes.sample
          redirect_to randomly_selected_recipe and return #exits, doesn't continue processing
        else
          flash[:error] = "Please enter an existing ailment."
        end
      end


      if params[:search].size == 0 || affliction.nil? # there's no recipes
        # flash[:error] = "Please enter an ailment."
        redirect_to '/'   
      else
        respond_to do |format|
          format.html { render action: "show" }
          format.js
        end
      end
    end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/ailments_helper.rb
module AilmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ailments/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Green Smoothie Generator</title>
        <meta name="description" content="">
        <meta name="author" content="">


        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->


       <!-- Include GOOGLE Webfonts -->

       <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>




        <!-- Include CSS Resources -->

        <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet">
        <link href="css/theme.css" rel="stylesheet">
        <link href="css/bootstrap/bootstrap-responsive.min.css" rel="stylesheet">
        <link href="css/font-awesome.css" rel="stylesheet">
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

    </head>

  <body>



   <!-- Start Navbar -->


    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Dust off that Nutribullet, people!</a>
          <div class="nav-collapse">
          </li>
            </ul>
           <ul class="nav pull-right">
              <li><%= link_to "Home", "/" %></li>
              <li><a href="http://www.rebootwithjoe.com/eating/a-z-fruit-veggies">Learn</a></li>
              <li><a href="mailto:athenspie@gmail.com">Contact</a></li>
            </ul>


          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>



   <!-- End Navbar -->



   <!-- Start Billboard -->

    <div class="billboard">
    <div class="container">
    <div class="row">
    <div class="span6">


   <h1 style="font-weight:400;"><span style="font-weight:400;">Something vexes thee?</h1>
           <br>
           <p>Enter your ailment... The green smoothie generator will find a recipe for you that features ingredients shown to improve your affliction.  Pineapple's <a href="http://umm.edu/health/medical/altmed/supplement/bromelain">bromelain</a> enzymes for inflammation, <a href="http://www.forbes.com/sites/melaniehaiken/2012/06/30/5-surprising-foods-that-help-you-sleep/">melatonin</a>-rich cherries for insomnia, ginger's <a href="http://health.howstuffworks.com/wellness/natural-medicine/herbal-remedies/using-ginger-to-treat-upset-stomach.htm">gingerols and shogaols</a> for upset belly... let food be thy medicine!  (Or at least a medicinal supplement.)</p>
           <br>
           <p>The Green Smoothie Generator currently dispenses both smoothie and juice recipes.</p>
                  <br>
            <div class="btn-toolbar">
      <a href="http://www.rebootwithjoe.com/eating/a-z-fruit-veggies"><button class="btn btn-large btn-head-1"> <i style="padding-right:15px; padding-top:5px;" class="icon-leaf"></i>Health Benefits of Foods</button></a>
      <a href="http://foodmatters.tv/articles-1/juicing-vs-blending-which-one-is-better"><button class="btn btn-large"><i style="padding-right:15px; padding-top:5px;" class="icon-star-empty"></i>Juicing vs. Blending</button></a>
       </div>

        <br>

      </div>

   	<div class="search-form" >
		<h1 class="logo">Green Smoothie Generator</h1>

			<img src="http://fc06.deviantart.net/fs41/i/2009/042/9/a/Ghost_in_a_Blender_by_venkman_project.jpg" alt="Juice" width="250" height="200">

		<%= form_tag recipes_path, :method => :get do %>
  		<div class="ui-widget">
    	<%#= collection_select_tag 'name', Ailment.all, :id, :name, { include_blank: "" } %>
      	<%= search_field_tag :search, params[:search], id: "tags", class: "search-query", size: "50", :placeholder => "Select an ailment" %>
      	<%= submit_tag "Search", :name => nil, class: "btn btn-danger btn-lg", id: "search-submit" %>
	    	<div>
	      	<%= flash[:error] %>
	    	</div>
  		</div>
		<% end %><br>
	</div>

<div id="recipe-result">
</div>

</div>
</div>
</div>
</div>

   <!-- End Billboard -->



     <!-- Start Main Content -->


<div class="sec_2">
<div class="container">
<div class="row">
<div class="span6">
<ul class="thumbnails">

<li class="span2">
<div class="fancycaption fancycaption-fade">
<img class="fade" width="150px" src="<%= asset_path("acne.jpg") %>" alt="">
</div>
</li>

 <li class="span2">
 <div class="fancycaption fancycaption-fade">
 <img class="fade" width="150px" src="<%= asset_path("colds.jpg") %>" alt="">
 </div>
 </li>

 <li class="span2">
 <div class="fancycaption fancycaption-fade">
 <img class="fade" width="150px" src="<%= asset_path("gout.jpg") %>" alt="">
 </div>
 </li>
 </ul></div>
 <div class="span6">
 <h1>vegetables.  yum.</h1>
 <br>
 <p class="disclaimer"><strong>obligatory disclaimer:</strong><br>
    Nutrition is a supplement, not a substitute, for conventional medicine.  Please consider food allergies, carb/fruit sugar content, medicine contraindications, etc. before consuming new foods.  Or ask a <a href="http://www.eatright.org/programs/rdfinder/">Registered Dietitian</a>.</p>
</div>
</div>
</div>
</div>

<div class="billboard">
<div class="container">
<div class="row">
<div class="span4 text-cent">
<div class="icon-helper">
<i class="fa-shopping-cart icon-large"></i>
</div>
<h2><a href="http://www.localharvest.org/farmers-markets/">Farmers' Market Locator</a></h2>
<p>Find a greenmarket or CSA near you!  Growers all over the world gather weekly to sell their produce directly to the public.  Shopping at a farmers' market is a great way to meet local farmers and get fresh, flavorful produce.</p>
</div>
<div class="span4 text-cent">
<div class="icon-helper">
<i class="fa-medkit icon-large"></i>
</div>
<h2><a href="http://www.drugs.com/drug_interactions.html">Check for Food Interactions</a></h2>
<p>Drug interactions occurs when the effect of a particular drug is altered when it is taken with another drug, or with food. Drugs.com provides a simple Drug Interaction Checker that will display any interactions between your chosen drug(s) and food.</p>
</div>
<div class="span4 text-cent">
<div class="icon-helper">
<i class="fa-heart icon-large"><a href="http://cdn.diabeticlivingonline.com/sites/diabeticlivingonline.com/files/styles/slide/public/CarbsSlide1.jpg?itok=vAFiFCrB"></a></i>
</div>
<h2><a href="http://www.umassmed.edu/healthyheart/tipsheets/carbcount.aspx">Carb Content</a></h2> 
<p>Search for carb content, calories, sugar and other nutritional info for any food.  It's super important to be aware of carb and sugar amounts, as smoothies, even green ones, may contain high levels.  Know your grub! </p>
</div>
</div>
</div>
</div>

<div class="container">
<hr>

      <!-- Example row of columns -->
      <div class="row">
         <div class="span3">
        <ul class="thumbnails">

        <li class="span3 span3 fancycaption fancycaption-fade">
  <img class="fade thumbnail" src="<%= asset_path("what-do-you-expect-hes-an-onion.jpg") %>" alt="" />
        </li>
      </ul>

        </div>
        <div class="span3">
        <ul class="thumbnails">

        <li class="span3 fancycaption fancycaption-fade">

  <img class="fade thumbnail" src="<%= asset_path("that-crazy-broccoli.jpg") %>" alt="" />

        </li>
      </ul>

        </div>
        <div class="span3">
          <ul class="thumbnails">

        <li class="span3 span3 fancycaption fancycaption-fade">
  <img class="fade thumbnail" src="<%= asset_path("vegetables-i-hate-pt-3-and-4-1.jpg") %>" alt="" />
</div>
        </li>
      </ul>

        <div class="span3">
          <ul class="thumbnails">

        <li class="span3 span3 fancycaption fancycaption-fade">
  <img class="fade thumbnail" src="<%= asset_path("pumpkin-pie.jpeg") %>" alt="" />
      <hr>

   </li>
   </ul>
   </div>
   </div>
   <hr>


   </div>

   <!-- End Main Content -->


     <!-- Start Footer -->

   <div id="footer">
   <div class="container">
   <div class="row">
   <div class="span6">  <p style="padding-top:15px;">&copy; 2014 - Made by <strong><a href="https://github.com/ChavaLovesFyedka">Stephanie</a></h6></strong> at Flatiron School</p></div>

    <div class="span6">  <div style="padding:10px; float:right;" class="btn-group">
  	<a href="https://www.facebook.com/sharer/sharer.php?u=http://greensmoothie-generator.herokuapp.com/"><button class="btn"><i  class="icon-facebook-sign"></i></button></a>
	<a href="https://twitter.com/home?status=%23GreenSmoothieGenerator:%20pick%20an%20ailment%20and%20get%20a%20recipe%20w/ingredients%20shown%20to%20improve%20it!%20http://greensmoothie-generator.herokuapp.com"><button class="btn"><i  class="icon-twitter-sign"></i></button></a> </div></div>

</div>
</div>
</div>


<!-- End Footer -->



    <!-- Include JQUERY/JAVASCRIPT
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="js/jquery.js"></script>
    <script src="js/bootstrap/bootstrap.min.js"></script>
    <script src="js/index.js"></script>
    <script src="js/rand.js"></script>
    <script src="js/bootstrap/fancyCaption.js"></script>

   <script>
     $(document).ready(function() {

  $('.shuffle').randomImage({path: 'images/'});
  $('a:first').click(function() {
    location.reload();
    return false;
  });

});


 </script>
     
   <script type="text/javascript">
$(document).ready(function(){
  $(".fancycaption-fade").fancyCaption({slideTopBar:false, slideBottomBar:false, slideLeftBar:false, slideRightBar:false });
});
</script>





</body></html>

app/views/ailments/update.html.erb
<h1>Ailments#update</h1>
<p>Find me in app/views/ailments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Greensmoothie</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'green_smoothie.png' %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/show.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Green Smoothie Generator</title>
        <meta name="description" content="">
        <meta name="author" content="">


        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->


       <!-- Include GOOGLE Webfonts -->

       <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>




        <!-- Include CSS Resources -->

        <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet">
        <link href="css/theme.css" rel="stylesheet">
        <link href="css/bootstrap/bootstrap-responsive.min.css" rel="stylesheet">
        <link href="css/font-awesome.css" rel="stylesheet">


    </head>

  <body>



   <!-- Start Navbar -->


    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Dust off that Nutribullet, people!</a>
          <div class="nav-collapse">
          </li>
            </ul>
           <ul class="nav pull-right">
              <li><%= link_to "Home", "/" %></li>
              <li><a href="http://www.rebootwithjoe.com/eating/a-z-fruit-veggies">Learn</a></li>
              <li><a href="mailto:athenspie@gmail.com">Contact</a></li>
            </ul>


          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>



   <!-- End Navbar -->






     <!-- Start Main Content -->


<div class="sec_abt">
<div class="container">
<div class="row">
 <div class="span6">
 <h1><%= link_to @recipe.name.upcase, @recipe.url, :target => "blank" %></h1>
 <br>

    <p>Ingredients: </p>
    <p><%= simple_format(@recipe.description) %></p><br>
 </p>
 <div style="padding-left:30px; padding-top:20px;" class="btn-toolbar">

      <button class="btn btn-large"><%= link_to "Meh? Try again for a new recipe >>", "/" %></button>
       </div>

</div>
<div class="span6">
<ul class="thumbnails">



 <li class="span3">
 <div class="fancycaption fancycaption-fade">
 <img class="fade" width="300" src="<%= asset_path("icon_256.png") %>" alt="">
 </div>
 </li>

 <li class="span3">
 <div class="fancycaption fancycaption-fade">
 <img class="fade" width="300" src="<%= asset_path("vegicon.png") %>" alt="">
 </div>
 </li>
 </ul></div>

</div>
</div>
<br>
<br>
</div>






<div class="billboard">

<div class="container">
<div class="row">

<div class="span4"><ul class="thumbnails">
        <li class="span4">
          <a href="#" class="thumbnail">
            <img src="<%= asset_path("store.jpg") %>" alt="">
          </a>
        </li>
        <li class="span2">
          <a href="#" class="thumbnail">
            <img src="<%= asset_path("juices.jpg") %>" alt="">
          </a>
        </li>
        <li class="span2">
          <a href="#" class="thumbnail">
            <img src="<%= asset_path("truck.jpg") %>" alt="">
          </a>
        </li>
 
      </ul></div>
<div class="span8"><article>
  <header>
    <h2><a href="http://www.rebootwithjoe.com/find-a-juice-bar-in-your-area/">Juice Bar Locator</a></h2>
  </header>

  <aside>
    Don't have a fancy blender?  On the go?  Find a juice bar near you.
  </aside>

  <p>Reboot with Joe offers a cool feature to help you find a juice bar in your area.  The 
Juice Bar Locator congregates the juice bars closest to you on a map. All you have to do is enter in your location and you’ll be walking out the door to your neighborhood juice bar.  It’s helpful for when you’re at home, at the office, and traveling so you can always have a juice in hand.
</p>
  <p>Check out the <a href="http://www.rebootwithjoe.com/find-a-juice-bar-in-your-area/">Juice Bar Locator</a> and Juice On!</p>

</article>






        </div>







</div>




     <hr style="margin: 18px 0;
border: 0;
border-top: 2px dashed #E5E5E5;
border-bottom: 2px dashed white;">

    <div class="container">
    <div class="row">


        <div class="span8">  <article>
  <header>
    <h2><a href="http://www.healwithfood.org/">Heal Your Body With Food!</a></h2>
  </header>

  <aside>
    HealWithFood.org provides condition-specific nutrition guides as well as general healthy eating tips to help you make that switch.
  </aside>

      <p>Daily Tips, Weekly Articles, Superfood Series, Useful Kitchen Tools and Information. Condition specific nutrition guides to 50+ common conditions.</p>
      <p>Bodyforming:  Abdominal fat, cellulite, excess body fat, overweight, sugar cravings, varicose veins.</p>
      <p>Skin, hair, nails: acne, psoriasis, wrinkles, eczema, hair loss, bruises.</p>      
      <p>Digestive: constipation, bloating, hemmorhoids, flatulence, gallstones.</p>
      <p>Afflictions: cardiovascular, cancer, allergies, rhinitis, asthma, PMS, PCOS, UTI, colds, fever blisters, arthritis, migraines, kidney stones, canker sores, nasal polyps, hives.</p>

</article>
</div>
                <div class="span4">  <ul class="thumbnails">

        <li class="span2">
          <a href="http://www.healwithfood.org/acne/" class="thumbnail">
            <img src="<%= asset_path("acne-foods.JPG") %>" alt="">
          </a>
        </li>

          <li class="span2">
          <a href="http://www.healwithfood.org/asthma/" class="thumbnail">
            <img src="<%= asset_path("asthma-foods.gif") %>" alt="">
          </a>
        </li>
         <li class="span4">
          <a href="http://www.healwithfood.org/" class="thumbnail">
            <img src="http://www.healwithfood.org/images_recipes/no_image.gif" alt="">
          </a>
        </li>

      </ul></div>




    </div>
    </div>







</div>
</div>

<div class="container">
<hr>

      <!-- Example row of columns -->
 <div class="tabbable tabs-left">
        <ul class="nav nav-tabs">
          <li class=""><a href="#lA" data-toggle="tab">Eat</a></li>
          <li class=""><a href="#lB" data-toggle="tab">These</a></li>
          <li class="active"><a href="#lC" data-toggle="tab">Foods</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane" id="lA">


<div class="container"><ul class="thumbnails">
        <li class="span2">
          <a href="http://www.healwithfood.org/health-benefits/kale-superfood.php" class="thumbnail">
            <img src="<%= asset_path("kale2.jpg") %>" alt="">          
          </a>
        </li>
        <li class="span2">
          <a href="http://www.healwithfood.org/health-benefits/bok-choy-cabbage-leaves.php" class="thumbnail">
            <img src="<%= asset_path("bokchoy.JPG") %>" alt="">
          </a>
        </li>
        <li class="span2">
          <a href="http://www.healwithfood.org/medicinal-uses/garlic-healing-properties.php" class="thumbnail">
            <img src="<%= asset_path("garlic.JPG") %>" alt="">
          </a>
        </li>
        <li class="span2">
          <a href="http://www.healwithfood.org/health-benefits/broccoli-nutritional.php" class="thumbnail">
            <img src="<%= asset_path("broccoli.JPG") %>" alt="">
          </a>
        </li>
          <li class="span2">
          <a href="http://www.healwithfood.org/health-benefits/eating-red-onions.php" class="thumbnail">
            <img src="<%= asset_path("redonions.JPG") %>" alt="">
          </a>
        </li>
      </ul></div>

          </div>
          <div class="tab-pane" id="lB">


           <div class="container"><ul class="thumbnails">
        <li class="span2">
          <a href="http://www.healwithfood.org/health-benefits/romaine-lettuce-cos.php" class="thumbnail">
            <img src="<%= asset_path("romaine.JPG") %>" alt="">
          </a>
        </li>
        <li class="span2">
          <a href="http://www.healwithfood.org/superfoods/brussels-sprouts-health-benefits.php" class="thumbnail">
            <img src="<%= asset_path("brusselssprouts.JPG") %>" alt="">
          </a>
        </li>
        <li class="span2">
          <a href="http://www.healwithfood.org/health-benefits/pomegranate-seeds-juice.php" class="thumbnail">
            <img src="<%= asset_path("pomegranate.JPG") %>" alt="">
          </a>
        </li>
        <li class="span2">
          <a href="http://www.healwithfood.org/health-benefits/mangosteen-fruit-powder.php" class="thumbnail">
            <img src="<%= asset_path("mangosteen.JPG") %>" alt="">
          </a>
        </li>
          <li class="span2">
          <a href="http://www.healwithfood.org/health-benefits/purple-carrots-nutrition-vs-orange-cultivars.php" class="thumbnail">
            <img src="<%= asset_path("purplecarrot.JPG") %>" alt="">
          </a>
        </li>
      </ul></div>


          </div>
          <div class="tab-pane active" id="lC">


          <div class="container"><ul class="thumbnails">
        <li class="span2">
          <a href="http://www.healwithfood.org/health-benefits/dandelion-greens-edible-leaf-tea.php" class="thumbnail">
            <img src="<%= asset_path("dandelion.JPG") %>" alt="">
          </a>
        </li>
        <li class="span2">
          <a href="http://www.healwithfood.org/health-benefits/mustard-greens-anti-cancer-properties.php" class="thumbnail">
            <img src="<%= asset_path("mustards.JPG") %>" alt="">
          </a>
        </li>
        <li class="span2">
          <a href="http://www.healwithfood.org/superfoods/collard-greens-health-benefits.php" class="thumbnail">
            <img src="<%= asset_path("collards.JPG") %>" alt="">
          </a>
        </li>
        <li class="span2">
          <a href="http://www.healwithfood.org/health-benefits/swiss-chard-nutritional-benefits.php" class="thumbnail">
            <img src="<%= asset_path("swisschard.JPG") %>" alt="">
          </a>
        </li>
          <li class="span2">
          <a href="http://www.healwithfood.org/health-benefits/red-cabbage-vs-white.php" class="thumbnail">
            <img src="<%= asset_path("cabbage.JPG") %>" alt="">
          </a>
        </li>
      </ul></div>



          </div>
        </div>
      </div>
   </div>
   <hr>


   </div>

   <!-- End Main Content -->


     <!-- Start Footer -->

   <div id="footer">
   <div class="container">
   <div class="row">
   <div class="span6">  <p style="padding-top:15px;">&copy; 2014 - Made by <strong><a href="https://github.com/ChavaLovesFyedka">Stephanie</a></h6></strong> at Flatiron School</p></div>

    <div class="span6">  <div style="padding:10px; float:right;" class="btn-group">
    <a href="https://www.facebook.com/sharer/sharer.php?u=http://greensmoothie-generator.herokuapp.com/"><button class="btn"><i  class="icon-facebook-sign"></i></button></a>
  <a href="https://twitter.com/home?status=%23GreenSmoothieGenerator:%20pick%20an%20ailment%20and%20get%20a%20recipe%20w/ingredients%20shown%20to%20improve%20it!%20http://greensmoothie-generator.herokuapp.com"><button class="btn"><i  class="icon-twitter-sign"></i></button></a> </div></div>

</div>
</div>
</div>


<!-- End Footer -->



    <!-- Include JQUERY/JAVASCRIPT
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="js/jquery.js"></script>
    <script src="js/bootstrap/bootstrap.min.js"></script>
    <script src="js/index.js"></script>
    <script src="js/bootstrap/fancyCaption.js"></script>


   <script type="text/javascript">
$(document).ready(function(){
  $(".fancycaption-fade").fancyCaption({slideTopBar:false, slideBottomBar:false, slideLeftBar:false, slideRightBar:false });
});
</script>





</body></html>